### ISSUE TITLE
Generate SVD during building?

### ISSUE THREAD

**Issue by dpc** [japaric/cortex-m#30]
Hi,

So I am very impressed by all these arm crates, and after reading the blog entries wanted to try it out, and see if I can get something blinking on my Teensy Board.

I am wondering about the workflow here. In the [Rust your ARM microcontroller!](http://blog.japaric.io/quickstart/#the-cargo-project-template) blogpost manual SVD -> Rust crate conversion is described. I was wondering if this could be done automatically. Eg. in `build.rs` one could call some function to generate the necessary files during the build itself. Does such approach make sense?

BTW. Is there a place like IRC/gitter to hang around to lurk at the discussion around this crate?

**Comment by japaric** [comment]
Hey @dpc.

Thanks!

> Does such approach make sense?

It certainly can be done that way. What I personally do is just have pre-generated crates published on crates.io: like [this one](https://crates.io/crates/stm32f30x). IMO this is better than having the generation as part of the build process. The latter approach increases build time and adds requirements to the build: e.g. have `svd2rust` installed.

> Is there a place like IRC/gitter to hang around to lurk at the discussion around this crate?

#rust-embedded on irc.mozilla.org.

P.S. This issue is in the wrong place. This repo is about the `cortex-m` crate which only contains access to Cortex-M functionality common to all Cortex-M microcontrollers. So device specific stuff like svd2rust generated code has no place in this particular crate.

**Comment by dpc** [comment]
Thanks!
